### ISSUE TITLE
Deployment to Github pages

### ISSUE THREAD

**Issue by woctezuma** [magnobiet/svelte-gh-pages#2]
Same as https://github.com/sveltejs/template/issues/214

https://github.com/magnobiet/svelte-gh-pages/blob/de1fbf21f9289a1d20ff71f16ddc17784cd07232/public/index.html#L9-L13

**Comment by gngenius02** [comment]
The `package.json` is different and has scripts to deploy to GitHub pages. The rest of the svelte template is just there to have something to display.
